version: "3.3"
services:
   central:
      image: mupif
      build: .
      cap_add: # for wireguard
      - NET_ADMIN
      volumes:
      - ./persistent:/var/lib/mupif/persistent
      ports:
      - 51821:51821
